#! /bin/sh

# Startup Programs
sxhkd &
# startup.sh &


bspc config border_width		2
bspc config window_gap			12
bspc config external_rules_command	$XDG_CONFIG_HOME/bspwm/ext_rule

bspc config split_ratio			0.5
bspc config borderless_monocle		false
bspc config gapless_monocle		false
bspc config focus_follows_pointer	true
bspc config focused_border_color	'#A5A5A5'


