directory: ~/Music/beets                # Music home
library: ~/Music/musiclibrary.blb       # Beets database
import:
        move: yes                       # Move files to ~/Music/beets after importing.
        write: yes
plugins: permissions lastgenre fetchart ftintitle mpdupdate smartplaylist random embedart
embedart: 
        auto: yes                       # Embed album art into the music files

mpdupdate:
        host: localhost
        port: 6600

permissions:
        file: 644
        dir: 755
